"""Shell completion support for CIAM CLI."""

import argparse
from typing import List, Optional


# Static completion choices
REGIONS = ["us", "uk", "can", "anz"]
ENVS = ["dev", "qa", "uat", "prod"]


def generate_region_env_combinations() -> List[str]:
    """Generate all region-env combinations for shorthand completion."""
    return [f"{region}-{env}" for region in REGIONS for env in ENVS]


def region_completer(prefix: str, parsed_args: argparse.Namespace, **kwargs) -> List[str]:
    """Completer for --region option."""
    return [r for r in REGIONS if r.startswith(prefix)]


def env_completer(prefix: str, parsed_args: argparse.Namespace, **kwargs) -> List[str]:
    """Completer for --env option."""
    return [e for e in ENVS if e.startswith(prefix)]


def shorthand_completer(
    prefix: str, parsed_args: argparse.Namespace, **kwargs
) -> List[str]:
    """Completer for config use shorthand (e.g., us-qa)."""
    combinations = generate_region_env_combinations()
    return [c for c in combinations if c.startswith(prefix)]


def store_id_completer(
    prefix: str, parsed_args: argparse.Namespace, **kwargs
) -> List[str]:
    """Completer for --store-id option."""
    # TODO: Fetch actual store IDs from config or API if available
    # For now, return empty to let user type freely
    return []


def install_completers(parser: argparse.ArgumentParser) -> None:
    """Install custom completers for argcomplete."""
    try:
        import argcomplete
    except ImportError:
        return

    # Find subparsers and install completers
    for action in parser._subparsers._actions:
        if isinstance(action, argparse._SubParsersAction):
            # This is the top-level subparsers
            for choice_name, subparser in action.choices.items():
                if choice_name == "config":
                    # Install completers for config subcommands
                    _install_config_completers(subparser, argcomplete)
                elif choice_name in ("users", "groups", "orgs", "products"):
                    # Install completers for domain subcommands
                    _install_domain_completers(subparser, argcomplete)


def _install_config_completers(config_parser: argparse.ArgumentParser, argcomplete) -> None:
    """Install completers for config subcommand."""
    for action in config_parser._subparsers._actions:
        if isinstance(action, argparse._SubParsersAction):
            # config use subcommand
            if "use" in action.choices:
                use_parser = action.choices["use"]
                for sub_action in use_parser._actions:
                    if sub_action.dest == "shorthand":
                        sub_action.completer = shorthand_completer
                    elif sub_action.dest == "region":
                        sub_action.completer = region_completer
                    elif sub_action.dest == "env":
                        sub_action.completer = env_completer
                    elif sub_action.dest == "store_id":
                        sub_action.completer = store_id_completer


def _install_domain_completers(domain_parser: argparse.ArgumentParser, argcomplete) -> None:
    """Install completers for domain subcommands (users, groups, etc.)."""
    for action in domain_parser._subparsers._actions:
        if isinstance(action, argparse._SubParsersAction):
            for subcommand_name, subcommand_parser in action.choices.items():
                for sub_action in subcommand_parser._actions:
                    if sub_action.dest == "store_id":
                        sub_action.completer = store_id_completer


def generate_bash_completion_script() -> str:
    """Generate Bash completion script using argcomplete."""
    script = """# Bash completion for ciam.py
# Generated by argcomplete

# Use argcomplete if available
eval "$(register-python-argcomplete ciam.py)"
"""
    return script


def generate_zsh_completion_script() -> str:
    """Generate Zsh completion script."""
    script = """# Zsh completion for ciam.py
# Generated by argcomplete

# Enable Bash completion compatibility
autoload -U bashcompinit
bashcompinit

# Use argcomplete
eval "$(register-python-argcomplete ciam.py)"
"""
    return script


def generate_powershell_completion_script() -> str:
    """Generate PowerShell completion script."""
    script = '''# PowerShell completion for ciam.py
# Generated by CIAM CLI

# Register argument completer for ciam.py
$completer = {
    param($wordToComplete, $commandAst, $cursorPosition)

    # Build the command line for completion
    $cmdLine = $commandAst.ToString()
    $words = $cmdLine -split '\\s+'
    
    # Call ciam.py with special completion environment variables
    $env:_ARGCOMPLETE = "1"
    $env:_ARGCOMPLETE_IFS = [char]0x0b
    $env:COMP_LINE = $cmdLine
    $env:COMP_POINT = $cursorPosition
    
    try {
        $output = python ciam.py 2>$null
        if ($output) {
            $output -split [char]0x0b | Where-Object { $_ } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        }
    }
    finally {
        Remove-Item Env:\\_ARGCOMPLETE -ErrorAction SilentlyContinue
        Remove-Item Env:\\_ARGCOMPLETE_IFS -ErrorAction SilentlyContinue
        Remove-Item Env:\\COMP_LINE -ErrorAction SilentlyContinue
        Remove-Item Env:\\COMP_POINT -ErrorAction SilentlyContinue
    }
}

Register-ArgumentCompleter -CommandName ciam.py -ScriptBlock $completer
'''
    return script
